### ISSUE TITLE
Character Classes

### ISSUE THREAD

**Issue by igniuss** [igniuss/DiscordHackerWeek#6]
So, character classes is gonna be a big one..
I'd start small and just go with the essentials first

Warrior/Fighter (High attack power, mediocre health/armor)
Knight/Paladin (Mediocre attack power, high health/armor)
Thief/Rogue (Mediocre attack and health, but gold earned bonus)
Priest/Healer(Mediocre attack and health, but group HP bonus)

Thankfully we won't need to worry about mana or anything like that, just need to make sure we balance the attack & health stuff, depending on the difficulty level people head to. 

Any comments @JGray0705 ?

**Comment by JGray0705** [comment]
Classes have been created. Will need to fix the multipliers after some testing to see what works best. [commit](https://github.com/igniuss/DiscordHackerWeek/commit/ef416e9e911fea72682a90ace8c9fb1f1972e22f)
